# Generated by Django 3.2.15 on 2022-08-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'NES Tokyo'), (2, 'Dest A'), (3, 'Dest B'), (4, 'Dest C')], default=None, verbose_name='出勤場所名')),
                ('in_out', models.IntegerField(choices=[(1, 'IN'), (0, 'OUT')], default=None, verbose_name='IN/OUT')),
                ('rest_in', models.IntegerField(default=None, verbose_name='休憩入り')),
                ('rest_out', models.IntegerField(default=None, verbose_name='休憩戻り')),
                ('time', models.TimeField(verbose_name='打刻時間')),
                ('date', models.DateField(verbose_name='打刻日')),
                ('staff', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
