# Generated by Django 3.2.15 on 2022-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintaiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitattendance',
            name='rest_in',
        ),
        migrations.RemoveField(
            model_name='submitattendance',
            name='rest_out',
        ),
        migrations.AddField(
            model_name='submitattendance',
            name='rest_in_out',
            field=models.IntegerField(choices=[(1, 'IN'), (0, 'BACK')], default=None, verbose_name='休憩'),
        ),
    ]
