# Generated by Django 3.2.15 on 2022-08-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintaiapp', '0002_auto_20220812_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitattendance',
            name='rest_in_out',
        ),
        migrations.AlterField(
            model_name='submitattendance',
            name='in_out',
            field=models.IntegerField(choices=[(1, 'IN'), (2, 'OUT'), (3, 'REST_IN'), (4, 'REST_BACK')], default=None, verbose_name='IN/OUT'),
        ),
    ]
