# Generated by Django 3.2.15 on 2022-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kintaiapp', '0003_auto_20220812_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitattendance',
            name='in_out',
            field=models.IntegerField(choices=[(1, '出勤'), (2, '退勤'), (3, '休憩入り'), (4, '休憩戻り')], default=None, verbose_name='IN/OUT'),
        ),
        migrations.AddConstraint(
            model_name='submitattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'in_out', 'date'), name='kintai_unique'),
        ),
    ]
